FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["AuthApi/AuthApi.csproj", "AuthApi/"]
COPY ["Contracts/Contracts.csproj", "Contracts/"]

RUN dotnet restore "AuthApi/AuthApi.csproj"

COPY . .

RUN dotnet publish "AuthApi/AuthApi.csproj" \
    -c Release \
    -o /app/publish \
    --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080
ENV ASPNETCORE_ENVIRONMENT=Testing

EXPOSE 8080

ENTRYPOINT ["dotnet", "AuthApi.dll"]
