FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["WebApp/WebApp.csproj", "WebApp/"]
COPY ["Contracts/Contracts.csproj", "Contracts/"]

RUN dotnet restore "WebApp/WebApp.csproj"

COPY . .

RUN dotnet publish "WebApp/WebApp.csproj" \
    -c Release \
    -o /app/publish \
    --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080
ENV ASPNETCORE_ENVIRONMENT=Testing

EXPOSE 8080

ENTRYPOINT ["dotnet", "WebApp.dll"]
